version : "3"


services:
  web:
    build:
      context: .
      dockerfile: django_docker_file
    container_name: django_web
    volumes: 
      - ./src:/src
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
